// Generated by https://quicktype.io

export interface BookResponse {
  id: number;
  name: string;
  author: AuthorResponse;
  category: CategoryResponse;
  price: number;
  status: boolean;
}

export interface AuthorResponse {
  id: number;
  name: string;
  birthDate: string;
  country: string;
}

export interface CategoryResponse {
  id: number;
  name: string;
  file: string;
}
